services:
  counter-app:
    build: .
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: express-counter-app
    volumes:
      - ./files:/files
